name: test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --no-match-test testRef
        id: test

      - name: Run Forge tests (reference)
        run: |
          forge test -vvv --match-test testRef --ffi
        id: test-ref

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Halmos
        run: pip install git+https://github.com/a16z/halmos

      - name: Run Halmos
        run: |
          halmos -v -st --contract LibUint1024Test --function testProve --loop 256 --test-parallel --solver-parallel --solver-timeout-assertion 80000
          halmos -v -st --contract LibPrimeTest --function testProve --loop 256 --test-parallel
        id: test-halmos
